version: 1
formatters:
  default:
    format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
handlers:
  rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    maxBytes: 1000000
    backupCount: 5
root:
  level: INFO
  handlers: [rotating_file_handler]
